apiVersion: v1
kind: Service
metadata:
  name: {{ include "pylos.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pylos.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pylos.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  type: {{ .Values.backend.service.type }}
