apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pylos.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pylos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "pylos.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pylos.labels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: pylos
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: PYLOS_DATA_DIR
              value: {{ .Values.backend.dataDir }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}
