{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pylos-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pylos-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENCODE_API_KEY
      remoteRef:
        key: {{ .Values.secretStore.secretPath }}
        property: OPENCODE_API_KEY
    - secretKey: LEMONADE_API_KEY
      remoteRef:
        key: {{ .Values.secretStore.secretPath }}
        property: lemonade_api_key
{{- end }}
