{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pylos.name" . }}-ai1-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pylos-ai1-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: ai/ai1
        property: API_KEY
    - secretKey: NAME
      remoteRef:
        key: ai/ai1
        property: NAME
    - secretKey: PROJECT_NAME
      remoteRef:
        key: ai/ai1
        property: PROJECT_NAME
    - secretKey: PROJECT_NUMBER
      remoteRef:
        key: ai/ai1
        property: PROJECT_NUMBER

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pylos.name" . }}-ai2-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pylos-ai2-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: ai/ai2
        property: API_KEY
    - secretKey: NAME
      remoteRef:
        key: ai/ai2
        property: NAME
    - secretKey: PROJECT_NAME
      remoteRef:
        key: ai/ai2
        property: PROJECT_NAME
    - secretKey: PROJECT_NUMBER
      remoteRef:
        key: ai/ai2
        property: PROJECT_NUMBER

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pylos.name" . }}-ai3-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pylos-ai3-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: ai/ai3
        property: API_KEY
    - secretKey: NAME
      remoteRef:
        key: ai/ai3
        property: NAME
    - secretKey: PROJECT_NAME
      remoteRef:
        key: ai/ai3
        property: PROJECT_NAME
    - secretKey: PROJECT_NUMBER
      remoteRef:
        key: ai/ai3
        property: PROJECT_NUMBER
{{- end }}
