namespace: pylos

imagePullSecrets:
  - name: ghcr-auth

config: |
  {
    "version": 2,
    "server": {
      "port": 3000,
      "log_level": "info",
      "enable_logging": true,
      "disable_content_logging": false,
      "database_url": "env.DATABASE_URL"
    },
    "providers": {},
    "governance": {
      "virtual_keys": []
    }
  }

database:
  enabled: false
  url: ""
  existingSecret: ""
  existingSecretKey: "DATABASE_URL"

backend:
  name: pylos
  replicaCount: 2
  image:
    repository: ghcr.io/jzacharie/pylos
    tag: latest
    pullPolicy: Always
  service:
    port: 3000
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  dataDir: /data
  pvc:
    accessModes:
      - ReadWriteOnce
    size: 1Gi

ui:
  name: pylos-ui
  replicaCount: 1
  image:
    repository: ghcr.io/jzacharie/pylos-ui
    tag: latest
    pullPolicy: Always
  service:
    port: 80
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

dev:
  enabled: false
  name: pylos-dev
  replicaCount: 1
  image:
    repository: ghcr.io/jzacharie/pylos
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  dataDir: /data
  pvc:
    accessModes:
      - ReadWriteOnce
    size: 1Gi

