ALTER TABLE organizations ADD COLUMN tags JSONB NOT NULL DEFAULT '[]';
ALTER TABLE teams ADD COLUMN tags JSONB NOT NULL DEFAULT '[]';
ALTER TABLE access_groups ADD COLUMN tags JSONB NOT NULL DEFAULT '[]';
