ALTER TABLE organizations ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE teams ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE access_groups ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
